// File generated by AgriVyn Firebase Setup
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for AgriVyn project (agrivyn-ai).
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAD8GTsKiFWtx9kQiUMdsAuenh1jSyENQ',
    appId: '1:225257498887:web:f78cdfade3c5cd8b08bda2',
    messagingSenderId: '225257498887',
    projectId: 'agrivyn-ai',
    authDomain: 'agrivyn-ai.firebaseapp.com',
    storageBucket: 'agrivyn-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWEw3V0Hw1x74mteMWiBieXibun6j0s8c',
    appId: '1:225257498887:android:0ba95a2621f6b5ea08bda2',
    messagingSenderId: '225257498887',
    projectId: 'agrivyn-ai',
    storageBucket: 'agrivyn-ai.firebasestorage.app',
  );
}
